"""
Document Generator — creates MRPL-branded Word documents from Qwen output.
Accepts optional structured extraction fields to render a proper table.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional
import datetime

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


# Output directory (backend/outputs/)
_OUTPUTS_DIR = Path(__file__).resolve().parents[2] / "outputs"
_OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)


def generate_approval_note(
    content: str,
    filename: str = "approval_note.docx",
    extracted_fields: Optional[dict] = None,
) -> str:
    """
    Generate a professional MRPL-branded Word document.

    Parameters
    ----------
    content : str
        Body text (model response).
    filename : str
        Output filename, saved under backend/outputs/.
    extracted_fields : dict, optional
        Structured fields parsed from OCR extraction — rendered as a
        key-value table at the top of the document if provided.

    Returns
    -------
    str
        Filename (not full path) — used by the /outputs download endpoint.
    """
    doc = Document()

    # ── MRPL Header ────────────────────────────────────────────────────────
    h = doc.add_paragraph()
    h.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = h.add_run("MANGALORE REFINERY AND PETROCHEMICALS LIMITED")
    r.bold = True
    r.font.size = Pt(15)
    r.font.color.rgb = RGBColor(0, 51, 102)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sr = sub.add_run("AntarAI Sovereign AI Workbench — Auto-Generated Document")
    sr.font.size = Pt(10)
    sr.font.color.rgb = RGBColor(100, 100, 100)

    doc.add_paragraph("")

    # ── Document metadata table ────────────────────────────────────────────
    meta = doc.add_table(rows=4, cols=2, style="Light Grid Accent 1")
    _cell(meta, 0, 0, "Date / Time")
    _cell(meta, 0, 1, datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    _cell(meta, 1, 0, "Model")
    _cell(meta, 1, 1, "Qwen3-8B-Q4_K_M (Local, Air-Gapped)")
    _cell(meta, 2, 0, "Classification")
    _cell(meta, 2, 1, "CONFIDENTIAL — Internal Use Only")
    _cell(meta, 3, 0, "Status")
    _cell(meta, 3, 1, "PENDING APPROVAL")

    doc.add_paragraph("")

    # ── Extracted fields table (if available) ──────────────────────────────
    if extracted_fields:
        doc.add_heading("Extracted Report Information", level=2)
        field_labels = [
            ("inspection_id", "Inspection ID"),
            ("equipment", "Equipment / Tag"),
            ("inspection_date", "Inspection Date"),
            ("finding", "Key Finding"),
            ("severity", "Severity"),
            ("recommended_action", "Recommended Action"),
        ]
        ext_table = doc.add_table(rows=len(field_labels), cols=2, style="Light Shading Accent 1")
        for i, (key, label) in enumerate(field_labels):
            _cell(ext_table, i, 0, label, bold=True)
            _cell(ext_table, i, 1, extracted_fields.get(key, "N/A"))
        doc.add_paragraph("")

    # ── Body content ──────────────────────────────────────────────────────
    doc.add_heading("AI-Generated Analysis", level=2)
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue
        # Render markdown-style headings as Word headings
        if stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=3)
        elif stripped.startswith("**") and stripped.endswith("**"):
            p = doc.add_paragraph()
            run = p.add_run(stripped.strip("*"))
            run.bold = True
        else:
            doc.add_paragraph(stripped)

    # ── Summary (if available) ─────────────────────────────────────────────
    if extracted_fields and extracted_fields.get("summary"):
        doc.add_paragraph("")
        doc.add_heading("Summary", level=2)
        doc.add_paragraph(extracted_fields["summary"])

    # ── Footer ────────────────────────────────────────────────────────────
    doc.add_paragraph("")
    footer_para = doc.add_paragraph()
    fr = footer_para.add_run(
        "This document was generated by AntarAI on-premise AI workbench using "
        "Qwen3-8B-Q4_K_M (Qwen/Qwen3-8B-GGUF). "
        "No data was transmitted outside the local network. "
        "AWAITING SUPERVISOR APPROVAL before official use."
    )
    fr.font.size = Pt(8)
    fr.font.color.rgb = RGBColor(130, 130, 130)
    fr.italic = True

    # ── Save ──────────────────────────────────────────────────────────────
    out_path = _OUTPUTS_DIR / filename
    doc.save(str(out_path))
    return filename


def _cell(table, row: int, col: int, text: str, bold: bool = False) -> None:
    """Helper to set table cell text."""
    cell = table.rows[row].cells[col]
    cell.text = text
    if bold:
        for para in cell.paragraphs:
            for run in para.runs:
                run.bold = True
