"""
Document Generator — creates Word / Excel / PPT files from model output.
"""

from pathlib import Path
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import datetime


# Output directory (backend/outputs/)
_OUTPUTS_DIR = Path(__file__).resolve().parents[2] / "outputs"
_OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)


def generate_approval_note(content: str, filename: str = "approval_note.docx") -> str:
    """
    Generate a professional Word document from the provided content.

    Parameters
    ----------
    content : str
        The body text (typically the model's response).
    filename : str
        Output filename.  Saved inside ``backend/outputs/``.

    Returns
    -------
    str
        The filename of the generated document (relative path usable by the API).
    """
    doc = Document()

    # ── Header ────────────────────────────────────────────────────────────
    header_para = doc.add_paragraph()
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = header_para.add_run("MANGALORE REFINERY AND PETROCHEMICALS LTD")
    run.bold = True
    run.font.size = Pt(16)
    run.font.color.rgb = RGBColor(0, 51, 102)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub.add_run("AntarAI — Sovereign AI Generated Document")
    sub_run.font.size = Pt(11)
    sub_run.font.color.rgb = RGBColor(100, 100, 100)

    doc.add_paragraph("")  # spacer

    # ── Metadata table ────────────────────────────────────────────────────
    table = doc.add_table(rows=3, cols=2, style="Light Grid Accent 1")
    cells = table.rows[0].cells
    cells[0].text = "Date"
    cells[1].text = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    cells = table.rows[1].cells
    cells[0].text = "Classification"
    cells[1].text = "CONFIDENTIAL — Internal Use Only"

    cells = table.rows[2].cells
    cells[0].text = "Generated By"
    cells[1].text = "AntarAI (Local, Air-Gapped)"

    doc.add_paragraph("")  # spacer

    # ── Body content ──────────────────────────────────────────────────────
    doc.add_heading("Report Content", level=2)
    for para_text in content.split("\n"):
        if para_text.strip():
            doc.add_paragraph(para_text.strip())

    # ── Footer disclaimer ─────────────────────────────────────────────────
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        "⚠ This document was generated by AntarAI on-premise AI workbench. "
        "No data was transmitted outside the local network."
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)

    # ── Save ──────────────────────────────────────────────────────────────
    out_path = _OUTPUTS_DIR / filename
    doc.save(str(out_path))
    return filename
