import { FileText, FolderOpen, Search, UploadCloud } from 'lucide-react'
import { Icon } from '../components/ui/Icon'
import { Panel } from '../components/ui/Panel'
import { StatusBadge } from '../components/ui/StatusBadge'

const documents = [
  { name: 'MRPL Process Safety Manual', type: 'PDF', detail: 'Operations / safety', size: '12.4 MB', state: 'Indexed' },
  { name: 'CDU-04 Maintenance Register', type: 'PDF', detail: 'Maintenance / CDU', size: '4.8 MB', state: 'Indexed' },
  { name: 'HSE Incident Response SOP', type: 'PDF', detail: 'HSE / procedures', size: '2.1 MB', state: 'Indexed' },
  { name: 'Refinery Throughput Baseline', type: 'XLSX', detail: 'Planning / analytics', size: '860 KB', state: 'Pending index' },
]

export function KnowledgeBaseView() {
  return <div className="space-y-6 panel-enter">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="eyebrow mb-2">Local document index</div><h2 className="text-xl font-semibold tracking-tight text-slate-100 sm:text-2xl">Knowledge base</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-muted sm:text-sm">Keep operational references available to local agents without syncing them to a cloud service.</p></div><button className="inline-flex min-h-11 items-center justify-center gap-2 border border-signal/35 bg-signal-dim/35 px-4 text-xs font-semibold uppercase tracking-[0.08em] text-signal hover:bg-signal-dim"><Icon icon={UploadCloud} size={16} />Upload document</button></div>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_280px] lg:items-start"><Panel className="overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-line px-4 py-4 sm:flex-row sm:items-center sm:px-5"><div><div className="eyebrow mb-1">Documents</div><h3 className="section-title">Indexed references <span className="ml-1 font-mono text-[10px] font-normal text-muted">/ {documents.length}</span></h3></div><label className="flex h-9 items-center gap-2 border border-line bg-ink/30 px-3 text-xs text-muted"><Icon icon={Search} size={14} /><span className="sr-only">Search documents</span><input className="w-full bg-transparent text-xs text-slate-200 outline-none placeholder:text-slate-600" placeholder="Filter documents" /></label></div><div className="divide-y divide-line/70">{documents.map((document) => <div key={document.name} className="flex items-center gap-3 px-4 py-4 transition-colors hover:bg-raised/20 sm:px-5"><span className="flex size-9 shrink-0 items-center justify-center border border-line bg-ink/35 text-signal"><Icon icon={document.type === 'PDF' ? FileText : FolderOpen} size={16} /></span><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-slate-200">{document.name}</div><div className="mt-1 text-[10px] text-muted">{document.detail} <span className="px-1 text-slate-700">/</span> {document.size}</div></div><StatusBadge tone={document.state === 'Indexed' ? 'success' : 'neutral'} compact>{document.state}</StatusBadge></div>)}</div></Panel><Panel className="p-5"><div className="eyebrow mb-4">Index status</div><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center border border-signal/25 bg-signal-dim/45 text-signal"><Icon icon={FolderOpen} size={19} /></span><div><div className="text-sm font-medium text-slate-100">Local only</div><div className="mt-1 text-[10px] text-muted">4 references registered</div></div></div><div className="mt-6 space-y-3 border-t border-line pt-5 text-xs"><div className="flex justify-between"><span className="text-muted">Vector store</span><span className="font-mono text-signal">localhost</span></div><div className="flex justify-between"><span className="text-muted">Last indexed</span><span className="font-mono text-slate-300">Today, 09:42</span></div></div><div className="mt-5 border-l-2 border-warning/50 bg-warning/10 px-3 py-2.5 text-[10px] leading-4 text-warning">Document ingestion is shown with sample records for this prototype.</div></Panel></div>
  </div>
}
